### PR TITLE
Fix State Details Page Rework Bugs

### LINKED ISSUE #148: Fix bugs on state page
1. Duplicate image: The water heat pump and stove are showing up twice on mobile view

2. Text mismatch: The text here is two difference sizes

3. Language should be consistent: MW, not megawatts or Megawatts. And actually, we can shorten the language, since it's wall of text RN: "In all, we'll need to build 12GW or wind and 11GW of solar.<br><br> That means building TKMW of wind turbines and TKMW of solar panels every year."

4. Spacing issue:

### PR DESCRIPTION
**Pull request by vkoves**
## Overview

Fixes issues with my latest state details page, like tight spacing and duplicate images (which I think was caused by a React HTML error)

This also includes some improvements to the wording and spacing of the sections that say how much pollution is dropped. I made the text clarify _what_ dropped the emissions (more clear, more screen-shottable) and experimentally made them fade in for emphasis:

| Before | After |
| --- | --- |
|  Screenshot from 2022-08-28 21-31-43 | Screenshot from 2022-08-28 21-31-54 |

Fade In Text Demo:

Peek 2022-08-28 21-41

**Note:** I just tacked in the fade in behavior. If folks don't like it, let me know and I can remove it!

Closes #148

### Demo

See description.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* Test the state details page on mobile and desktop, confirming spacing is never too tight (with elements touching) and all images are what you expect

### CODE REVIEW

File: src/components/state-details.js [hunk 1]
```diff
@@ -389,7 +384,7 @@ export default function StateDetailsPage ({ location, data }) {
                 />
               </div>
               <div className="col h3">
-                <p className="h2 mt-2 mb-0">
+                <p className="mt-2 mb-0">
```
Comment (vkoves) [inline src/components/state-details.js:387]: A lot of my changes were removing `h2` and `h3` from paragraphs. We shouldn't individually be setting the size of these as it made nearly impossible to keep them consistent on such a large page. I instead moved this to CSS and only use classes to change font size when a paragraph is supposed to be smaller or larger than normal for this page (`.h2`)

**Review by derekeder — DISMISSED** [review]
@vkoves looks good!

I'm not really a fan of the fade animation, so I'd opt to remove it.

**Comment by vkoves** [comment]
@derekeder - the fade in has gone the way of the Dodo
