### PR TITLE
Annual Counts Fix for Vehicles & Buildings

### LINKED ISSUE #127: count of buildings and cars to replace don't account for already changed
The current calculation for number of buildings electrified takes the total buildings in the state and divides it by the number of years to 2050 (28). This does not account for the buildings already electrified. We should subtract that from the total and calculate the change / year from there. Same with cars

For Illinois buildings:

* current: 5.2M buildings / 28 = 187,000 per year
* should be: 5.2M buildings * (1 - 20% electrified already) / 28 = 148,571 per year

For Illinois cars:

* current: 4.2M buildings / 28 = 150,000 per year
* should be: 4.2M buildings * (1 - 0.6% electrified already) / 28 = 149,100 per year

### PR DESCRIPTION
**Pull request by derekeder**
## Overview

This pull request updates the calculations we make counting cars and buildings to be electrified to account for the already electrified percentages. Slightly changes the order of the text and bar chart so we establish the percentage before we account for it in the annual count.

Additional changes:
* small spacing fixes for links on the about page
* updates link to Climate Cabinet to a custom ActBlue URL

Closes #127

### Demo

**Buildings** 

before
Screen Shot 2022-07-20 at 10 00 53 PM

after
Screen Shot 2022-07-20 at 10 00 08 PM

**Cars**

before
Screen Shot 2022-07-20 at 10 01 38 PM

after
Screen Shot 2022-07-20 at 10 01 46 PM

## Testing Instructions

* view the state detail pages and confirm the building and vehicle counts look accurate
* check states like Alaska and Hawaii that have no building electrification percentage info
* check the about page and confirm we don't have any links without spaces around them

### CODE REVIEW

File: src/components/state-details.js [hunk 1]
```diff
@@ -126,14 +126,19 @@ export default function StateDetailsPage ({ location, data }) {
     Cars_All: carsAll,
     EV_Registration: evRegistration,
   } = data.allVehiclesJson.edges[0].node
+  
   const pctEv = Math.round((evRegistration / carsAll) * 100 * 10) / 10
   const pctNonEv = Math.round((100 - pctEv) * 10) / 10
+
+  // calculate cars remaining to electrify
+  const carsToElectrify = carsAll * (pctNonEv/100)
```
Comment (vkoves) [inline src/components/state-details.js:134]: We already have `evRegistration `, why not just do `carsAll - evRegistration`? Or you could do `carsAll * pctNonEv`

File: src/components/state-details.js [hunk 2]
```diff
@@ -126,14 +126,19 @@ export default function StateDetailsPage ({ location, data }) {
     Cars_All: carsAll,
     EV_Registration: evRegistration,
   } = data.allVehiclesJson.edges[0].node
+  
   const pctEv = Math.round((evRegistration / carsAll) * 100 * 10) / 10
   const pctNonEv = Math.round((100 - pctEv) * 10) / 10
```
Comment (vkoves) [inline src/components/state-details.js:131]: These roundings are gross, I'd suggest doing `num.toFixed(2)`  which yields a string, and doing that to create an output string (if that's what we're trying to do).

Comment (derekeder) [reply src/components/state-details.js:131]: i didn't write this code but it looks to be accounting for Javascript's floating point inaccuracy. These are numbers used to calculate values and the strings are formatted below.

File: src/components/state-details.js (hunk 1 above)
Comment (derekeder) [reply src/components/state-details.js]: sure - subtraction is easier. change made

**Comment by vkoves** [comment]
@derekeder - I will say, it feels a bit confusing only giving the total after the % graph, since by the time you are looking at the graph it doesn't mean anything yet.

Maybe we can say something like (for both sections):

> There are 4.2 million cars in Illinois, but 26,000 of them are already EVs! We need to electrify the remaining 4.1 million cars, around 149,000 a year.

> [ Graph ] 


Or:

> There are 4.2 million cars in Illinois, but 26,000 of them are already EVs!

> [ Graph ] 

> We need to electrify the remaining 4.1 million cars, around 149,000 a year.

**Comment by derekeder** [comment]
@vkoves ok went with your first suggestion for both buildings and vehicles

**Review by vkoves — CHANGES_REQUESTED** [review]
One last thing I noticed, pretty sure this should be either "and X% of building _systems_ are..." or "and X% of _buildings' systems_ are...": (systems is correct in being plural but the possessive doesn't make sense - what does the systems possess?)

Screenshot from 2022-07-25 15-21-31

**Review by vkoves — APPROVED** [review]
Looks great to me!
